### ISSUE TITLE
别最后写你测出多少多少漏洞，你能实际用你的工具测试一下，写出过程吗？假大空！

### ISSUE THREAD

**Issue by iot-firmeware** [NSSL-SJTU/SaTC#12]

**Comment by bob777sjtu** [comment]
详细测试过程可以参考其他厂商的报告：
https://mp.weixin.qq.com/s/DIaWUyLRuUXeaNr6NRPncA
https://mp.weixin.qq.com/s/zHiBVe-1hVM-llC7S2ws4w
我们不可能把每个固件的测试过程都罗列到这里，有任何问题欢迎沟通！
