### ISSUE TITLE
when i construct docker image, it occured error, what should i do .

### ISSUE THREAD

**Issue by jesson3264** [NSSL-SJTU/SaTC#17]
```
 Running setup.py develop for angr
    Running command /home/satc/.virtualenvs/SaTC/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/satc/deps/angr-dev/angr/setup.py'"'"'; __file__='"'"'/home/satc/deps/angr-dev/angr/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
    running develop
    Building angr_native
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/satc/deps/angr-dev/angr/setup.py", line 125, in <module>
        'angr': ['lib/*']
      File "/home/satc/.virtualenvs/SaTC/local/lib/python2.7/site-packages/setuptools/__init__.py", line 162, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/satc/deps/angr-dev/angr/setup.py", line 77, in run
        self.execute(_build_native, (), msg='Building angr_native')
      File "/usr/lib/python2.7/distutils/cmd.py", line 349, in execute
        util.execute(func, args, msg, dry_run=self.dry_run)
      File "/usr/lib/python2.7/distutils/util.py", line 309, in execute
        func(*args)
      File "/home/satc/deps/angr-dev/angr/setup.py", line 30, in _build_native
        import unicorn
      File "/home/satc/.virtualenvs/SaTC/local/lib/python2.7/site-packages/unicorn/__init__.py", line 4, in <module>
        from .unicorn import Uc, uc_version, uc_arch_supported, version_bind, debug, UcError, __version__
      File "/home/satc/.virtualenvs/SaTC/local/lib/python2.7/site-packages/unicorn/unicorn.py", line 110
        print("Found an old style dynamic library libunicorn.so, consider checking your installation", file=sys.stderr)
                                                                                                           ^
    SyntaxError: invalid syntax
  Rolling back uninstall of angr

```

**Comment by jesson3264** [comment]
> ```
>  Running setup.py develop for angr
>     Running command /home/satc/.virtualenvs/SaTC/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/satc/deps/angr-dev/angr/setup.py'"'"'; __file__='"'"'/home/satc/deps/angr-dev/angr/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
>     running develop
>     Building angr_native
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/home/satc/deps/angr-dev/angr/setup.py", line 125, in <module>
>         'angr': ['lib/*']
>       File "/home/satc/.virtualenvs/SaTC/local/lib/python2.7/site-packages/setuptools/__init__.py", line 162, in setup
>         return distutils.core.setup(**attrs)
>       File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
>         dist.run_commands()
>       File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
>         self.run_command(cmd)
>       File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
>         cmd_obj.run()
>       File "/home/satc/deps/angr-dev/angr/setup.py", line 77, in run
>         self.execute(_build_native, (), msg='Building angr_native')
>       File "/usr/lib/python2.7/distutils/cmd.py", line 349, in execute
>         util.execute(func, args, msg, dry_run=self.dry_run)
>       File "/usr/lib/python2.7/distutils/util.py", line 309, in execute
>         func(*args)
>       File "/home/satc/deps/angr-dev/angr/setup.py", line 30, in _build_native
>         import unicorn
>       File "/home/satc/.virtualenvs/SaTC/local/lib/python2.7/site-packages/unicorn/__init__.py", line 4, in <module>
>         from .unicorn import Uc, uc_version, uc_arch_supported, version_bind, debug, UcError, __version__
>       File "/home/satc/.virtualenvs/SaTC/local/lib/python2.7/site-packages/unicorn/unicorn.py", line 110
>         print("Found an old style dynamic library libunicorn.so, consider checking your installation", file=sys.stderr)
>                                                                                                            ^
>     SyntaxError: invalid syntax
>   Rolling back uninstall of angr
> ```

I modified the Dockerfile, **ADD --chown=satc:satc http://202.120.7.23:8888/deps/angr-dev.tar.xz /home/satc/deps/**  modifed to **ADD --chown=satc:satc ./deps/angr-dev.tar.xz /home/satc/deps/**, it's ok. Maybe the source file of **http://202.120.7.23:8888/deps/angr-dev.tar.xz** has some error.

**Comment by FallinSlee** [comment]
您好！打扰了，我遇到了和您相同的问题，希望您能分享一下是如何解决的

**Comment by jesson3264** [comment]
我没再继续弄这个了



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年02月10日 15:42 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [NSSL-SJTU/SaTC] when i construct docker image, it occured error, what should i do . (Issue #17) |

您好！打扰了，我遇到了和您相同的问题，希望您能分享一下是如何解决的
