### ISSUE TITLE
Fail to analyze `/usr/sbin/lighttpd` of Vigor 2960 v1.5.1.3 

### ISSUE THREAD

**Issue by Cossack9989** [NSSL-SJTU/SaTC#2]
![image](https://user-images.githubusercontent.com/32336251/129511083-3eb75af9-2d3d-41ff-a347-dc74924b2083.png)
SaTC succeeded to analyze the cgi of Vigor 2960 v1.5.1.3, but failed to analyze `/usr/sbin/lighttpd`, the command is 
`python satc.py -d /targetfs/ -o ../lighttpd_result/ --ghidra_script=ref2sink_bof --ghidra_script=ref2sink_cmdi --taint_check -b /usr/sbin/lighttpd`

**Comment by Cossack9989** [comment]
`/usr/sbin/apmd` and `/usr/sbin/cvmd` also failed

**Comment by smile0304** [comment]
The command i used:
`python satc.py -d /home/satc/vigor/ -o ../res/ --ghidra_script=ref2sink_bof --ghidra_script=ref2sink_cmdi --taint_check -b lighttpd`

![image](https://user-images.githubusercontent.com/20963266/129513683-c004e438-df3c-49b2-95c9-4d6509195af1.png)


Use the `-b` parameter only to specify the filename

You can try the following command:
`python satc.py -d /targetfs/ -o ../lighttpd_result/ --ghidra_script=ref2sink_bof --ghidra_script=ref2sink_cmdi --taint_check -b lighttpd`

**Comment by Cossack9989** [comment]
`-b lighttpd` may confuse SaTC to analyze `/etc/init.d/lighttpd` but not `/usr/sbin/lighttpd`

**Comment by smile0304** [comment]
SaTC has not considered this situation for the time being. 

You can temporarily solve this problem by renaming the `lightppd` under `/usr/sbin`

**Comment by smile0304** [comment]
Close this issue
