### ISSUE TITLE
TypeError in taint_check

### ISSUE THREAD

**Issue by Cossack9989** [NSSL-SJTU/SaTC#3]
![image](https://user-images.githubusercontent.com/32336251/129514566-4b44a0c3-41a5-4be0-9a5b-b3bbc70db07f.png)
What I use is V1.0 docker image of SaTC

**Comment by harden614** [comment]
我也是出在summary_function 不过不是这个错

**Comment by Cossack9989** [comment]
大概浏览了一下，可能是snprintf读第二个参数的时候读进来了False而不是字符串？

**Comment by smile0304** [comment]
这个问题不会影响分析的结果。忽略就好
