### ISSUE TITLE
 Multiple function definitions for __sigsetjmp at EXTERNAL:00000011 found.  No function signature applied. (ApplyFunctionDataTypesCmd)  

### ISSUE THREAD

**Issue by mz21g** [NSSL-SJTU/SaTC#6]
![image](https://user-images.githubusercontent.com/22990076/135186216-f2f32fac-fb3d-4764-aa00-c56a3440bbfb.png)
执行到这一步会卡住是怎么回事呀？
使用的是docker hub的镜像 
```bash
docker pull smile0304/satc
```
具体命令为：
```bash
python satc.py -d /home/squashfs-root/ -o /home/satc/res  --ghidra_script=ref2sink_cmdi --ghidra_script=ref2sink_bof --taint_check
```
固件是解密后的文件

**Comment by smile0304** [comment]
方便的话提供一下固件吧。根据这个日志看应该是正常运行的，可能是分析文件太大导致程序假死

**Comment by mz21g** [comment]
可以给我一个联系方式吗？我把固件给你

**Comment by mz21g** [comment]
固件是我自己解密的加密固件，不太方便，可以给我一个联系方式吗？我单独传给你

**Comment by mz21g** [comment]
老哥，固件发你谷歌邮箱了，抽时间麻烦看一下

**Comment by smile0304** [comment]
我初步看了下您提供的固件，这个固件应该是个升级包，并不是一个完整的固件，所以在定位边界服务时已经出问题了，并且，静态资源文件也并不完整。你可以尝试从设备中将整个文件系统打包出来再做分析。

**Comment by mz21g** [comment]
明白了，那等我把整个文件系统提出来再试一下，谢谢啦
